### ISSUE TITLE
Ripple effect incompatible with Tailwind CSS

### ISSUE THREAD

**Issue by zhuoyue95** [aforemny/material-components-web-elm#103]
I have been using Tailwind CSS with my project. Today when I tried to integrate this package into my project and make use of material design components, I ran into an issue with ripple effect on buttons, in which the ripple effect just didn't fire. 

Looking into the issue, I discovered that [something](https://github.com/tailwindcss/tailwindcss/blob/51d0dd3252f0e4f2b59b19484f2bd8b2777fd2c9/src/plugins/css/preflight.css#L102) in the `preflight.css` has meddled with the functionality. More specifically, the 
```css
* {
  border-style: solid;
}
```
rule has crippled the ripple effect not only on buttons, but also the ripple effect altogether.

Tested on:
Chrome 80.0.3987.163 on macOS 10.15.3
Elm 0.19.1

A minimal example:

```elm
module Main exposing (main)

import Browser exposing (Document)
import Html exposing (button, div, node, text)
import Html.Attributes exposing (class)
import Material.Button exposing (buttonConfig, outlinedButton, raisedButton, textButton, unelevatedButton)



-- Main --


main : Program () () Never
main =
  Browser.document
    { init = \_ -> ( (), Cmd.none )
    , view = view
    , update = \_ _ -> ( (), Cmd.none )
    , subscriptions = always Sub.none
    }



-- View --


view : () -> Document Never
view _ =
  { title = "MDC"
  , body =
      [ node "style" [] [ text "* {border-width: 0; border-style: solid;}" ]
      , div []
          [ textButton { buttonConfig | additionalAttributes = heroMargin } "Text"
          , raisedButton { buttonConfig | additionalAttributes = heroMargin } "Raised"
          , unelevatedButton { buttonConfig | additionalAttributes = heroMargin } "Unelevated"
          , outlinedButton { buttonConfig | additionalAttributes = heroMargin } "Outlined"
          ]
      ]
  }


heroMargin : List (Html.Attribute msg)
heroMargin =
  [ Html.Attributes.style "margin" "16px 32px" ]

```

**Comment by aforemny** [comment]
Hi @zhuoyue95, I think this should probably be solved upstream. I have found a [relevant issue](https://github.com/material-components/material-components-web/issues/5061).

**Comment by aforemny** [comment]
A work-around is potentially to unset tailwind's border style for class `.mdc-ripple-surface--test-edge-var-bug`.

**Comment by aforemny** [comment]
I think this should be solved elsewhere. If you feel this issue needs solving here, please re-open.

**Comment by aforemny** [comment]
It seems there has been [some progress upstream](https://github.com/material-components/material-components-web/pull/5264).
