### ISSUE TITLE
Wrong requires on Elm Packages

### ISSUE THREAD

**Issue by iliocatallo** [aforemny/material-components-web-elm#105]
Hi,

I'm under the impression that the `require`s reported on [Elm packages](https://package.elm-lang.org/packages/aforemny/material-components-web-elm/2.1.2/) are wrong. The README here on GitHub correctly reports

```javascript
require("material-components-web-elm/dist/material-components-web-elm.js");
require("material-components-web-elm/dist/material-components-web-elm.css");
```

Whereas on Elm packages the same section reads

```javascript
require("material-components-web/dist/material-components-web.js");
require("material-components-web/dist/material-components-web.css");
```

(The difference is in the missing  `-elm` suffix).

Thank you,
Best,
Ilio.

**Comment by aforemny** [comment]
Hi @iliocatallo, thank you very much for reporting this! I am currently preparing the next release, and so this should be fixed on Elm package shortly.
