### ISSUE TITLE
TextField/TextArea reject all input

### ISSUE THREAD

**Issue by hallelujahdrive** [aforemny/material-components-web-elm#112]
As the title says, it's about a bug in `TextField`/`TextArea`.

When `TextField`/`TextArea` is used in `form`, validation message is displayed at the time of submit and it is not submitted.

The cause is that `textField_.pettern` is initialized with `""` in the `connectedCallback` of `MdcTextField`.
This initial value is not appropriate because the `""` regular expression means that only text of zero length is allowed.
The `pattern` attribute is present when some value is assigned, so you can avoid this problem by not assigning a value in `connectedCallback`.
Or if you don't need the `pattern` attribute in the first place, this won't happen unless you use `form`.

I needed a `form` so I modified the code to not initialize the `pattern` attribute and thought about sending a pull request.
However, before that, I was curious that I was assigning initial values ​​to the attributes of `textField_` in `connectedCallback`. It looks like they don't need them. (Also for other custom-elements).

Please let me know if you have a reason to assign initial values ​​to them. If you have no particular reason or problem, fix the initialization in `connectedCallback` to solve the title problem.

**Comment by aforemny** [comment]
Hi @hallelujahdrive, thanks a bunch for raising this issue!

I have implemented a slightly less obvious solution to the problem in c2bab283951291f4d9eada56bb23cf2524734a17, and I hope this fixes the issue that you described!

I copied some background information [here](https://gist.github.com/aforemny/2512cb8356ba296cb7e13342178ce495).

**Comment by hallelujahdrive** [comment]
Hi @aforemny, thanks for fixing the bug and publishing background information.

I was confused by your implementation being more complex than the solution I was thinking of, but I think I understand why.
The method without assigning an initial value doesn't consider changing the `pattern` attribute during execution, so I think your implementation is appropriate.
