### ISSUE TITLE
Misleading/Wrong documentation for Material.List.Item.graphic in combination with Icon 

### ISSUE THREAD

**Issue by j340m3** [aforemny/material-components-web-elm#117]
Section: List Item with Graphic
Issue: The example code uses Icon.config, which isn't present anymore. Should be replaced by "[]"
Link: https://package.elm-lang.org/packages/aforemny/material-components-web-elm/latest/Material-List-Item

**Comment by aforemny** [comment]
Hi @j340m3, thank you for reporting this! This seems to be fixed in [the latest version](https://package.elm-lang.org/packages/aforemny/material-components-web-elm/latest/Material-List-Item#list-item-with-graphic).

**Comment by j340m3** [comment]
As far as I can see, it isn't. Or has it been changed again in 6.0.0?
