### ISSUE TITLE
onClick handler not being set on dynamically-added tabs

### ISSUE THREAD

**Issue by shaydon** [aforemny/material-components-web-elm#138]
Hi. I am finding that when an additional `Tab` is added as the final child of an existing `TabBar`, it does not generate click messages despite my having configured it to do so via `Tab.setOnClick`. Investigating in dev tools indicates there is no click event handler attached to the button element.

I suspect this is really a virtual-dom issue. I worked around it using `Html.Keyed.node` with the `TabBar` keyed to the number of tabs, so that the whole bar is re-rendered each time a tab is added.

Here is [an Ellie showing the issue](https://ellie-app.com/c4GP53NTXLsa1). Press "+1" to add a fifth tab, note that the new tab cannot be selected.

(I have seen #37, however my issue appears to occur outside of the context of Hot Module Reloading also.)

Tested only on Chrome so far.

**Comment by aforemny** [comment]
Hi @shaydon, this is fixed in master via 9878e539a88f5cf322889d6762cb333bf67ef749. Thank you for reporting this!
