### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by bowbahdoe** [aforemny/material-components-web-elm#165]
Are there plans to integrate the date picker component?

**Comment by aforemny** [comment]
> Are there plans to integrate the date picker component?

That would entirely depend on the upstream project: https://github.com/material-components/material-components-web/search?q=date+picker&type=issues

In the meantime, IMO [native date pickers](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) work well enough. This is achievable using [TextField.setType](https://package.elm-lang.org/packages/aforemny/material-components-web-elm/latest/Material-TextField#setType).
