### ISSUE TITLE
Source list items do not work

### ISSUE THREAD

**Issue by simonh1000** [aforemny/material-components-web-elm#43]
at least on Chrome

![image](https://user-images.githubusercontent.com/5256724/67164133-4cffc880-f377-11e9-9574-4f01b511c7e4.png)

**Comment by aforemny** [comment]
Hi @simonh1000, thank you for reporting this! I have updated List to accommodate link list items (ed610b03bddb98a115d14e3881addb54507f48ac) and I have updated the [demo](https://aforemny.github.io/material-components-web-elm/).
