### ISSUE TITLE
Can you explain how this works

### ISSUE THREAD

**Issue by simonh1000** [aforemny/material-components-web-elm#44]
I'm working on the assumption that at root we are now working with web components, and so all the wiring up of effects that was needed before and which made earlier attempts to implement mdi in Elm so hard, is now much much simpler? Is that correct?

**Comment by aforemny** [comment]
Hi @simonh1000, that is correct. Let me elaborate:

We are now using custom elements (essentially web components minus shadow DOM) to encapsulate each material component from material-components-web. This means we can rely on their CSS **and** JS to integrate with Elm. (In previous attempts we used only the CSS and attempted to implement the JS from the components in Elm.) Thus now our Elm implementation is merely a wrapper around the expected DOM structure and much simpler.

Contrasting the current API with, say, elm-mdc's, we are no longer required to maintain a "styling state" of components (`Material.Model`) and we no longer have to be able to dispatch internal as well as user messages from components (`Material.Msg msg -> msg`).

On the other hand, we are now concerned with writing the custom elements for this approach, but that has mostly been straight-forward so far.

I hope that this helps answer your question. If anything remains unclear feel free to follow up!

**Comment by simonh1000** [comment]
Oh this is brilliant. I would suggest you add that the README as I suspect many got their fingers burnt trying the old approaches and you will want to emphasise that you've eradicated the boilerplate.

By the way: I'm not sure I agree with the distinction `custom elements (essentially web components minus shadow DOM) ` - I though custom elements and we components were synonyms. But it's not an important point, and feel free to close this
