### ISSUE TITLE
cannot install library

### ISSUE THREAD

**Issue by eweise** [aforemny/material-components-web-elm#45]
I tried elm install aforemny/material-components-web-elm with both elm version 0.19.0 and 0.19.1 but elm could not find the library. Is it published?

**Comment by simonh1000** [comment]
looks like it https://package.elm-lang.org/packages/aforemny/material-components-web-elm/latest/

**Comment by aforemny** [comment]
Hi @eweise, the published version is not yet compatible with 0.19.1. I do not foresee any obstacles, I just have not tested it yet. I will try to test it during the weekend and publish an updated version that is compatible with both 0.19.0 and 0.19.1.

As with version 0.19.0 you should have no trouble installing the library. Are you sure you are actually using 0.19.0? You can verify by running `elm version`. What is the error message that you are getting? Possibly other dependencies in your elm.json create a conflict. If this is  not a fresh project, could you please share your elm.json?

Btw. currently package.elm-lang.org seems to be down. We will have to wait for that to resolve first.

**Comment by eweise** [comment]
Hi @aforemny looks like I have have 0.19.1 installed. I thought setting my elm.json back to "elm-version": "0.19.0" would force elm to use that version but apparently that's not what it does. I'll see if I can revert back to 0.19.0 until the this library is release for 0.19.1. Very cool library btw.

**Comment by aforemny** [comment]
Thanks! I'll leave this open until I've released the 0.19.1 version.

**Comment by aforemny** [comment]
Fixed in 28bc7481474f375048b46683571c51784731d0ec.

**Comment by aforemny** [comment]
Hi @eweise, just a quick heads up that version 1.0.1 with Elm 0.19.1 support has been released.
