### ISSUE TITLE
Invalid on TextField doesn't set the CSS Class

### ISSUE THREAD

**Issue by alexanderkiel** [aforemny/material-components-web-elm#54]
If I mark a TextField as invalid using:
```
textField { textFieldConfig | invalid = True }
```
it doesn't set the CSS class `mdc-text-field--invalid` and so it doesn't get red.

**Comment by aforemny** [comment]
Hi @alexanderkiel, thank you for reporting this. This is fixed in the current master and I will include this fix in the next release.
