### ISSUE TITLE
Ability to focus a TextField

### ISSUE THREAD

**Issue by aforemny** [aforemny/material-components-web-elm#66]

**Comment by alexanderkiel** [comment]
Either autofocus or allow to give the input element and id so we can focus with `Browser.Dom.focus`.

**Comment by aforemny** [comment]
I have decided not to provide support for auto-focus, but rather provide support for `Browser.Dom.focus`. The reason is that the autofocus attribute has been unreliable in my experience, and I think `Browser.Dom.focus` is more of a proper solution given the fact that Elm uses virtual DOM diffing.

I have made some progress in the [focus-support](https://github.com/aforemny/material-components-web-elm/tree/focus-support) branch.

I have decided that we should provide focus support for the following elements:

- Button
- Card
- Checkbox
- FABs
- Icon Button
- Icon Toggle
- List
- Radio
- Select
- Slider
- Switch
- Tab bar
- Text field
- Form Field
- Chip Set

The following is still outstanding:

- [ ] Update documentation
- [ ] Test and implement support for Form Field
- [ ] Test and implement support for Chip Set
- [ ] Test and implement support for Browser.Dom.blur

**Comment by aforemny** [comment]
This is implemented in fae5d07cb1fde3dcc0e53091b67cf340add49346 and will be in the next release. @alexanderkiel thank you for your patience!

**Comment by alexanderkiel** [comment]
Thanks! Sorry I had no time to evaluate this before you finalized it.
