### ISSUE TITLE
Slider doesn't handle size change properly

### ISSUE THREAD

**Issue by bemyak** [aforemny/material-components-web-elm#69]
**How to reproduce**
1. Go to https://aforemny.github.io/material-components-web-elm/#slider
2. Open the side panel with "burger menu" button
3. Try to drag slider's pin

**Expected result**
Pin is dragged from the position it was at.

**Actual result**
Pin "jumps" right and is being dragged with a visible offset

**Comment by aforemny** [comment]
Hi @bemyak, thank you for reporting this. Curiously, it also happens in the [material-components-web demo](https://material-components.github.io/material-components-web-catalog/#/component/slider). I think it might be [this upstream bug](https://github.com/material-components/material-components-web/issues/5128).

**Comment by aforemny** [comment]
A fix for this [has been merged upstream](https://github.com/material-components/material-components-web/pull/5492). :tada:

**Comment by aforemny** [comment]
Implemented in 915cdbd0e156e6ccfd0498a62bb9a3bff0df80cc.
