### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setAttribute' of undefined

### ISSUE THREAD

**Issue by JesterXL** [aforemny/material-components-web-elm#72]
Anyone seeing this error? I've upgraded to v2.1.0. It _may_ be coming from an `iconButton`, but I'm not entirely sure. When I got to another page (i.e. route), that's when it starts.

![Screen Shot 2020-01-17 at 4 17 16 PM](https://user-images.githubusercontent.com/424737/72646769-ecb3ff00-3944-11ea-8f58-fbe8c770ab89.png)

**Comment by JesterXL** [comment]
The `iconButton` is a red herring, it's the List. If I comment it out, I stop getting the error. If I build a list with nothing in it, still get error, so doubt it's the `listItem` itself, but not sure.

**Comment by aforemny** [comment]
Hi @JesterXL, any chance you can trim down your code to a [SSCCE](http://www.sscce.org/)? I'd be happy to take a look at something that I can run. :-) Thanks!

**Comment by aforemny** [comment]
Hi @JesterXL, any chance I can get my hands on some code reproducing this error? It does not necessary have to be a SSCCE. I would be curious to see what is causing this.

**Comment by aforemny** [comment]
Closing this as stale. If you have some code reproducing this, please re-open.
