### ISSUE TITLE
Datatables trigger TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by SwiftEngineer** [aforemny/material-components-web-elm#74]
I noticed some errors on the my site. Checked and the demo site has them as well.

Error from demo site:
![Screen Shot 2020-02-10 at 7 01 06 PM](https://user-images.githubusercontent.com/20078622/74208460-7a2efa00-4c38-11ea-96b9-d12fc9eacfe1.png)

Looks like the cause is a typo in the custom datatable element class. I went ahead and made a quick PR to fix the issue:
https://github.com/aforemny/material-components-web-elm/pull/73

Cheers

**Comment by aforemny** [comment]
Fixed in 2.1.1. Thank you very much for your PR!
