### ISSUE TITLE
Label on TextField is lowered if input is removed

### ISSUE THREAD

**Issue by jonsa** [aforemny/material-components-web-elm#75]
With some text in a `TextField`, if I remove the text the label is lowered even if the input has focus. I have to unfocus and focus the input again or start typing for the label to be raised again.

Here's an [Ellie](https://ellie-app.com/7ZY3XXXWjPDa1) to demonstrate.

If I change `onInput = Just Update` to `onInput = Nothing` the label stays raised when the text is removed.

**Comment by jonsa** [comment]
Is this a bug or am I doing something wrong?

Here's a capture of what I'm experiencing
![input](https://user-images.githubusercontent.com/807381/74593021-8693c800-5027-11ea-9d44-f46374cca6c7.gif)

**Comment by aforemny** [comment]
Hi @jonsa, sorry for the late reply. I think it is a bug!

**Comment by aforemny** [comment]
Hi @jonsa, I cannot seem to reproduce this issue [on the demo](http://material-components-elm.lc/material-components-elm/#text-field). Could you please provide an example?

**Comment by aforemny** [comment]
Hi @jonsa, this should be fixed in acd7c8823345238efcb6689a9947c2746ad64b10. I will try to release version 2.1.2 shortly.

Thank you for reporting this issue!
