### ISSUE TITLE
Expose opaque configuration types, like Card.Button

### ISSUE THREAD

**Issue by QAFabianHuch** [aforemny/material-components-web-elm#77]
### Issue
Some configuration types should be exposed as opaque types, like `Card.button` and `Card.Icon`, so users can add type annotations to their code.
### Example
It is currently possible to do the following:
```elm
import Material.Card exposing (cardActionButton, buttonConfig)

renderButton msg =
    cardActionButton { buttonConfig | onClick = msg } "my button"
```

but annotating the type
```elm
renderButton : msg -> Material.Card.Button msg
```
does not compile, since `Card` does not expose `Button`.

### Versions
2.10, current master

### Fix
Expose those types, without their constructors.

**Comment by aforemny** [comment]
Current master exposes Card.Button and Card.Icon, so I am closing this. Thank you very much for reporting this!
