### ISSUE TITLE
Input Chip Set incorrectly makes chip invisible

### ISSUE THREAD

**Issue by QAFabianHuch** [aforemny/material-components-web-elm#81]
# Issue
Some components have bugs that are due to the underlying javascript implementation:
 - the `Chips.inputChipSet` component tries to make a chip invisible once the 'close' button is clicked. However, if the chip is removed via event, the next chip is made invisible (which was not targeted)
- the `Menu` onClose method can trigger with stale state, after the view has already updated. It's not clear to me what exactly causes this, and I can't seem to factor this bug out in a MWE. 

# Example
I have created an example for the input chip issue:
https://ellie-app.com/89cKqpqGztra1

# Possible Causes
In the chip example, the `mdc-chip__icon--trailing` class seem to cause this behaviour.

# Affected Version(s)
2.1.0, 2.1.1

**Comment by aforemny** [comment]
Hi @QAFabianHuch, the chip issue should be resolved with a7a2d98629c3a048965992aebb575a4342347e03. Thank you very much for reporting it!
