### ISSUE TITLE
Elm Package Documentation: Card: Expose PrimaryActionConfig

### ISSUE THREAD

**Issue by j340m3** [aforemny/material-components-web-elm#85]
Site in question: [Material.Card](https://package.elm-lang.org/packages/aforemny/material-components-web-elm/latest/Material-Card#primary-action-block)

I had to consult this repo to see all fields of PrimaryActionConfig. Would you consider to add its definition to the documentation?

**Comment by aforemny** [comment]
I have checked whether current master exposes all public types. There is no PrimaryActionConfig anymore, in particular. Thanks for reporting this issue!
