### ISSUE TITLE
JS Error when checkbox list has initially selected items

### ISSUE THREAD

**Issue by matsjoyce** [aforemny/material-components-web-elm#87]
Tested on version 2.1.2.

When a list containing checkboxes is created and `selected` is set for one of more list items, the following error is produced:  

```js
Uncaught Error: MDCListFoundation: Expected array of index for checkbox based list but got number: 0
    at MDCListFoundation.isIndexValid_ (foundation.js:420)
    at MDCListFoundation.setSelectedIndex (foundation.js:128)
    at MDCList.set [as selectedIndex] (component.ts:56)
    at HTMLElement.connectedCallback (custom-element.js:69)
    at _VirtualDom_applyPatchRedraw (elm.js:3798)
    at _VirtualDom_applyPatch (elm.js:3716)
    at _VirtualDom_applyPatchesHelp (elm.js:3702)
    at _VirtualDom_applyPatches (elm.js:3693)
    at elm.js:3948
    at _Browser_makeAnimator (elm.js:4009)
    at elm.js:3944
    at _Platform_initialize (elm.js:1879)
    at elm.js:3928
    at Object.init (elm.js:20)
    at elm.html:13
```

This appears to be due to: https://github.com/aforemny/material-components-web-elm/blob/c01ce82da33c8207bd9fcb0d5494a7a1ae1aa861/src/list/component.ts#L56-L59

`this.selectedIndex` is -1 when the element is initialised, and so the `(index as number[])[0]` is taken. However, MDC wants a list, and so errors occur. I'm not sure what the reason for the first branch is, so it might be unneeded.

MCVE:

```elm
module Main exposing (main)

import Material.List exposing (list, listConfig, listItem, listItemConfig, listItemMeta)
import Material.Checkbox as Checkbox exposing (checkbox, checkboxConfig)
import Browser

main =
  Browser.sandbox { init = 0, update = update, view = view }

update msg model = model

view model =
    list listConfig
        [ listItem { listItemConfig | selected = True }
            [ listItemMeta []
                [ checkbox
                    { checkboxConfig
                        | state = Checkbox.Checked
                    }
                ]
            ]
        ]
```

It can also be reproduced by:
 - Go to https://aforemny.github.io/material-components-web-elm/#lists
 - Open the browser console (to see the errors)
 - Scroll to the checkbox list example  and select one of the items
 - Navigate away from the lists page using the sidebar
 - Navigate back to the lists page
 - Console will start filling with errors

**Comment by aforemny** [comment]
See [my comment](https://github.com/aforemny/material-components-web-elm/issues/88#issuecomment-691727391) in #88.
