### ISSUE TITLE
List of checkboxes reanimate and trigger onChange messages when rerendered

### ISSUE THREAD

**Issue by matsjoyce** [aforemny/material-components-web-elm#88]
Tested on version 2.1.2 using Chrome 80

Each time a checkbox is checked, the already checked checkboxes reanimate and send onChange messages which then untoggles them.

![bug](https://user-images.githubusercontent.com/6631310/75681075-c6df8100-5c8a-11ea-88d1-d7b68b956865.gif)

MCVE:
```elm
module Main exposing (main)

import Set exposing (Set)
import Material.List exposing (list, listConfig, listItem, listItemConfig, listItemMeta)
import Material.Checkbox as Checkbox exposing (checkbox, checkboxConfig)
import Html exposing (text)
import Browser

type alias Model = Set Int
type Msg = ToggleCheckbox Int

main = Browser.sandbox { init = Set.empty, update = update, view = view }

update msg model =
    case msg of
        ToggleCheckbox i ->
            case Set.member i model of
                True ->
                    Set.remove i model
                False ->
                    Set.insert i model

view model =
    let
        checkbox_ index =
            checkbox
                { checkboxConfig
                    | onChange = Just (ToggleCheckbox index)
                    , state =
                        if Set.member index model then
                            Checkbox.Checked

                        else
                            Checkbox.Unchecked
                }

        listItem_ index =
            listItem listItemConfig
                [ text (String.fromInt index)
                , listItemMeta [] [ checkbox_ index ]
                ]
    in
    list listConfig (List.map listItem_ <| List.range 0 3)
```

**Comment by aforemny** [comment]
Hi @matsjoyce, thank you for raising this issue! If I am not mistaken, this is a known issue. As a work-around, please set `selected` on the list item iff its checkbox is `checked`.

Of course this is a bug. I just wanted to give some feedback and possibly a work-around before you spend a lot of time investigating this even more.

**Comment by matsjoyce** [comment]
No problem, I was just trying this as a workaround for #87. The previous issue was #42, which has been closed, so I opened this one in case there was a regression.

**Comment by matsjoyce** [comment]
@aforemny Related to this, if I have a list of checkboxes (using `selected`) and the underlying model changes due to some other user interaction, the checkboxes start flipping every render. 
Interestingly, if I comment out these lines: https://github.com/aforemny/material-components-web-elm/blob/c01ce82da33c8207bd9fcb0d5494a7a1ae1aa861/src/list/component.ts#L185-L187

It all seems to work fine with that code removed. Additionally, it fixes the unchecking bug shown above. The checkboxes still rerender each time, but they stay checked.

**Comment by aforemny** [comment]
Hi @matsjoyce, your observation is correct. I will reopen this anyways, because I would like to checkbox list to work even if one does not set selected. This requires making changes to `foundation.ts` rather than `component.ts` which we are currently not set up for.

**Comment by aforemny** [comment]
Updated example: https://ellie-app.com/9XJxgQgBpwfa1

**Comment by aforemny** [comment]
Hi @matsjoyce, I have _finally_ got around to updating our list implementation. Since we are allowing ourselves to update foundations for some time now, I have made the following changes to _our_ implementation of lists.

- List selection is completely handled within Elm.
- List selection always uses an array of numbers, even for single selection lists.

I think those changes while non-trivial make the integration with Elm a lot more robust since they match the Elm implementation better.

The relevant commit is 25c09293326ee5c14cc3b0de2e81d2ecfeafe237 and I am hopeful that it fixes #88, as well as #87 and #90. I will verify this in the Ellie examples once I released a new version, but my local verification seems to be promising.

Thank you very much for your input on these issues and for your patience.

**Comment by matsjoyce** [comment]
Thanks for looking at this! I will try the patch on my code as well, since I have it using a local build of this library.

**Comment by aforemny** [comment]
@matsjoyce I would appreciate that! I could not reproduce this issue any more in the Ellie (after updating the assets from 4.0.0 to 5.1.0). So I think this is solved. If you encounter any issues still, please re-open here or create a new one! Thanks again for your help in figuring this out!

**Comment by matsjoyce** [comment]
@aforemny I have updated my code base and this seems to work great!

**Comment by aforemny** [comment]
I am happy to hear that. Thank you very much for checking! :)
