### ISSUE TITLE
Drawers assume to be full page height

### ISSUE THREAD

**Issue by j340m3** [aforemny/material-components-web-elm#89]
SSCCE: https://ellie-app.com/8cphq6CkMQha1

The material components states [here](https://material.io/components/navigation-drawer/#modal-drawer) that drawers can also be "clipped" below the TopAppBar. Our Drawers seem to assume that they will be of the full page height and at the highest visible level. This leads in the "clipped" case to an unnecessary scrollbar on the right as well as that the Drawer will be Drawn over the TopAppBar while scrolled.

**Comment by matsjoyce** [comment]
You can fix this by (this is how https://aforemny.github.io/material-components-web-elm solves the problem):

 - Adding `additionalAttributes = [ style "z-index" "1" ]` to the drawer config
 - And adding `TopAppBar.fixedAdjust` to the drawer contents

See https://ellie-app.com/8ctpcQBcnBda1 for a working example. This seems to be deliberate, since the demoed way for drawers and app bars to interact in material-components-web (https://stackblitz.com/edit/mdc-drawer-demo?file=index.html) is to move the app bar.

**Comment by j340m3** [comment]
Ok yes, i forgot the fixed adjust on the example, my bad.
But I learned something new today. _z-index_! So this issue can be marked as solved, yet I'm asking myself if it would be good to mention this somewhere in the documentation? Or is there a way to adapt the implementations so that this is not necessary anymore?

**Comment by j340m3** [comment]
@matsjoyce Taking your last point into account:
Yes, it's demoed that way and I suppose therefore the recommended way to use this package, nevertheless in the aforementioned documentation, that a clipped drawer is also demoed and therefore there had to be a way to map this behaviour into this repo.

**Comment by matsjoyce** [comment]
Heh, don't be too happy. `z-index` is more of a curse then a help in my experience.

WRT adjusting the implementation: Essentially, both the top app bar and the drawer "float" on top of everything. The top app bar does it on level 4, while the drawer floats on level 6. To support your use case the drawer would need to be moved below the app bar, while for the "official" use case it probably needs to be the way it is currently.

Either way, the theming code is not changed by this package, so any adjustments would need to be made by the people at https://github.com/material-components/material-components-web.

It would be nice if we could make a collection of demos in elm, similar to what the material folks have done with stackblitz, but I'm not sure the best way to make that happen.

**Comment by j340m3** [comment]
It's the first time I hear of stackblitz (probably my bad :man_facepalming:), but it seems to be something similar to ellie (see first post). What features is ellie missing?

**Comment by matsjoyce** [comment]
I don't think ellie is missing any features, it's just we also need some sort of index of examples, maybe with screenshots. Stackblitz is what MDC used for some of their demos, I hadn't heard of it before either.

**Comment by aforemny** [comment]
As far as I understand, this is working as intended. Thanks to both of you!
