### ISSUE TITLE
Non-interactive changes to selection in a list of checkboxes produces elm messages

### ISSUE THREAD

**Issue by matsjoyce** [aforemny/material-components-web-elm#90]
Problem: If the model changes without the user interacting with a checkbox in a list, extra change messages get produces for each checkbox whose value changed. For example (all of the checkboxes get toggled at once):

![simplescreenrecorder-2020-03-03_16 28 47](https://user-images.githubusercontent.com/6631310/75797005-61fc5780-5d6c-11ea-9be9-4a8b619ba79a.gif)

The checkboxes should get toggled all at once, however:

 - On the first click, the model sets all of the checkboxes to `Checked`
 - This results in an additional three `ToggleCheckbox` messages which uncheck all of the checkboxes.
 - The second click then toggles the checkboxes back on again. No extra messages.
 - The third click unchecks the checkboxes, additional messages etc.
 - The result is that the visible state only changes every two clicks, while the model state is inconsistent with the visible state.

The reason this occurs is that an update occurs in the following way:

 - Elm renders the model, and starts updating the list.
 - `selectedIndex` is set on the `MDCList`. It sets the state of the checkboxes and fires the `change` events.
 - Elm receives those events and processes them. However, the `change` handler has not been updated, so it uses the old state for the comparison. Therefore it allows the change message to be sent onwards.
 - The `update` function does not know what the state of the checkbox is, only that it has changed. Therefore it assumes it changed, and toggles the model.

Possible fixes include:

 - Adding a flag that is set while `foundation_.setSelectedIndex` is executing, blocking event generation. This is probably the minimal change (I can put a PR together if you want, since I already have working code).
 - Modify a whole bunch of stuff to include on the event whether the event was caused by user interaction or programmatically.
 - Passing the checkbox state to the `onChange` function, which would be a breaking API change.
 - Something else.

MCVE:
```elm
module Main exposing (main)

import Set exposing (Set)
import Material.List exposing (list, listConfig, listItem, listItemConfig, listItemMeta)
import Material.Checkbox as Checkbox exposing (checkbox, checkboxConfig)
import Html exposing (text)
import Browser

type alias Model = Set Int
type Msg = ToggleCheckbox Int

main = Browser.sandbox { init = Set.empty, update = update, view = view }

update msg model =
    case Debug.log "msg" msg of
        ToggleCheckbox i ->
            case Set.member i model of
                True ->
                    Set.empty
                False ->
                    Set.fromList <| List.range 0 3

view model =
    let
        _ = Debug.log "model" model
        checkbox_ index =
            checkbox
                { checkboxConfig
                    | onChange = Just (ToggleCheckbox index)
                    , state =
                        if Set.member index model then
                            Checkbox.Checked

                        else
                            Checkbox.Unchecked
                }

        listItem_ index =
            listItem { listItemConfig | selected = Set.member index model }
                [ text (String.fromInt index)
                , listItemMeta [] [ checkbox_ index ]
                ]
    in
    list listConfig (List.map listItem_ <| List.range 0 3)
```

**Comment by aforemny** [comment]
Updated example: https://ellie-app.com/9kWWJMthVM2a1

**Comment by aforemny** [comment]
See [my comment](https://github.com/aforemny/material-components-web-elm/issues/88#issuecomment-691727391) in #88.
