### ISSUE TITLE
Elm Package Documentation: modalDrawerConfig does not have a field called onClick

### ISSUE THREAD

**Issue by j340m3** [aforemny/material-components-web-elm#91]
In the Example code for `modalDrawer`, the `modalDrawerConfig` gets the field `onClick` updated. This field does not exist (maybe id did in earlier versions).
The right field name is `onClose` as stated two elements below. 

[Link](https://package.elm-lang.org/packages/aforemny/material-components-web-elm/latest/Material-Drawer#modal-drawer)

**Comment by aforemny** [comment]
Hi @j340m3, thank you for reporting this! I fixed it in a55a64dde89b32929b1875cfb03bcbf40a554adb.
