### ISSUE TITLE
Modal Drawer: Error: Focus trap needs at least one focusable element

### ISSUE THREAD

**Issue by j340m3** [aforemny/material-components-web-elm#93]
SSCCE : 
https://ellie-app.com/8cRCJFbHX3sa1
I followed every documentation here on Modal Drawer that I could find, but somehow, my modalDrawer parts throw now errors on the javascript side.

**Comment by matsjoyce** [comment]
This error occurs when there are no interactive elements such as buttons or list items in your drawer. Once you add some content the error should go away. It's annoying but doesn't really happen once you've finished your UI.

**Comment by aforemny** [comment]
I think this should be mentioned in the documentation, but otherwise I do not see what we could do about it. Since the JavaScript error is merely a warning and not fatal, I am OK with this.

I leave this open until I update the documentation.

**Comment by aforemny** [comment]
I decided to close this without updating the documentation since the JS error is non-fatal, and quite descriptive. Thanks for both your input on this one!
